---
downloads: ~/.ansible-downloads/

config_from_git:
  - {
      repo: 'git@github.com:satblip/karabiner-elements-config.git',
      destination: '~/.config/karabiner',
    }

homebrew_installed_packages:
  - 1password-cli
  - gh
  - iperf
  - mas
  - node
  - nmap
  - npm
  - openssl
  - python
  - python3
  - redis
  - telnet
  - shellcheck
  - siege
  - sqlite
  - tldr
  - wget
  - zookeeper
  - zsh-autosuggestions
  - zsh-syntax-highlighting

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - adobe-creative-cloud
  - affinity-designer
  - another-redis-desktop-manager
  - audio-hijack
  - bruno
  - chirp
  - cockatrice
  - colorsnapper
  - coolterm
  - debookee
  - discord
  - drawio
  - dropbox
  - raspberry-pi-imager
  - farrago
  - firefox
  - firefox-developer-edition
  - google-chrome
  - gpg-suite
  - grandperspective
  - imageoptim
  - iterm2
  - karabiner-elements
  - keka
  - licecap
  - microsoft-excel
  - microsoft-edge
  - microsoft-powerpoint
  - microsoft-word
  - mqttfx
  - ngrok
  - notion
  - notion-calendar
  - obs
  - onyx
  - opera
  - orbstack
  - pocket-casts
  - postbox
  - postman
  - prusaslicer
  - qflipper
  - raycast
  - rectangle
  - saleae-logic
  - setapp
  - signal
  - slack
  - sourcetree
  - spotify
  - steam
  - sublime-text
  - surfshark
  - tinymediamanager
  - via
  - viscosity
  - visual-studio-code
  - vlc
  - wireshark
  - zoom

mas_installed_apps:
  - { id: 1352778147, name: 'Bitwarden (2024.2.0)' }
  - { id: 1500180529, name: 'UPS Power Monitor (1.5.9)' }
  - { id: 497799835, name: 'Xcode (15.3)' }
  - { id: 669289700, name: 'Sweet Home 3D (7.3.1)' }
  - { id: 937984704, name: 'Amphetamine (5.3.2)' }
  - { id: 1088670425, name: 'Cuprum (3.1.9)' }
  - { id: 442160987, name: 'Flycut (1.9.6)' }

# osx_script: "~/.osx --no-restart"

gem_packages: []

npm_packages:
  - name: eslint
    state: present
  - name: semistandard
    state: present
  - name: snazzy
    state: present
  - name: nyc
    state: present
  - name: eslint-config-standard
    state: present
  - name: eslint-plugin-import
    state: present
  - name: eslint-plugin-n
    state: present
  - name: eslint-plugin-promise
    state: present

pip_packages:
  - name: platformio
    state: present

vscode_packages:
  - artdiniz.quitcontrol-vscode
  - bmarkovic.haproxy
  - spywhere.guides
  - wholroyd.jinja
  - wmaurer.change-case
  - donjayamanne.githistory
  - druideinformatique.antidote
  - gruntfuggly.todo-tree
  - lokalise.i18n-ally
  - tyriar.sort-lines
  - christian-kohler.npm-intellisense
  - christian-kohler.path-intellisense
  - bruno-api-client.bruno
  - dbaeumer.vscode-eslint
  - platformio.platformio-ide
  - digitalbrainstem.javascript-ejs-support
  - ryanluker.vscode-coverage-gutters
  - github.copilot-chat
  - github.copilot
  - davidanson.vscode-markdownlint

post_provision_tasks: []
