---
- hosts: localhost
  connection: local

  vars_files:
    - config.yml
    - vars/apple-credentials.yml

  roles:
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
      ignore_errors: yes
    - role: geerlingguy.mac.mas
      when: mas_installed_apps
      tags: ['mas']
      ignore_errors: yes
    - role: osx
      tags: ['osx']

  tasks:
    - include_tasks: tasks/install-oh-my-zsh.yml
      tags: ['oh-my-zsh']

    - include_tasks: tasks/extra-packages.yml
      tags: ['extra_packages']

    - include_tasks: tasks/install-hack-font.yml
      tags: ['hack_font']

    - include_tasks: tasks/configuration.yml
      tags: ['configuration']

    - name: Run configured post-provision ansible task files.
      include_tasks: '{{ outer_item }}'
      loop_control:
        loop_var: outer_item
      with_fileglob: '{{ post_provision_tasks|default(omit) }}'
