---
- hosts: localhost
  connection: local

  vars_files:
    - config.yml
    - vars/apple-credentials.yml

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']

  tasks:
    - include_tasks: tasks/ansible-setup.yml

    # - include_tasks: tasks/osx.yml
    #   when: configure_osx
    #   tags: ['osx']

    - include_tasks: tasks/extra-packages.yml

    - include_tasks: tasks/install-fisherman.yml

    - include_tasks: tasks/install-hack-font.yml

    - include_tasks: tasks/configuration.yml

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
