---
- name: Check if oh-my-zsh is already installed
  stat:
    path: ~/.oh-my-zsh
  register: ohmyzsh_dir
  tags: ['oh-my-zsh']

- name: Setup oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  when: not ohmyzsh_dir.stat.exists
  tags: ['oh-my-zsh']

- name: Set zsh as default shell
  shell: chsh -s /bin/zsh
  become: true
  tags: ['oh-my-zsh']

- name: add zsh plugins to zshrc if not already there
  blockinfile:
    path: ~/.zshrc
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK - zsh plugins"
    block: |
      source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
      source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
  tags: ['oh-my-zsh']
